### ISSUE TITLE
ZIP OR ZIP FILE ISSUE 

### ISSUE THREAD

**Issue by Torotv** [card100/torminal#6]
![help](https://user-images.githubusercontent.com/21000033/30964676-73814342-a420-11e7-9421-52f40ca508b9.png)

That Is How IT Looks Affter You Donlowad Zipp. We Should Make it To Work as a extestion ( Unpacked) or Just Work with a Zip.

**Comment by card100** [comment]
Weird.
I tried on a Win 10 computer and got this:
![knvorz](https://user-images.githubusercontent.com/17168923/30986442-0f118f5a-a459-11e7-81c0-e0b555312dc7.jpg)

**Comment by Nanomotion** [comment]
The reason why it didn't work when you downloaded it as a ZIP was because of the file paths. If you were to open DevTools (`Ctrl+Shift+I`), then you could see that a file path like `/path/to/css.css`, which would make the browser look for the file in `C:\path\to\css.css`. One way you could fix this is by using relative file paths (E.g. `./path/to/css.css` or `path/to/css`), though I wouldn't recommend it as it could cause conflicts, depending on how you want to run the program.

**Comment by Torotv** [comment]
Okay. Well; we will add that soon. Namoamtion you have access?

**Comment by Nanomotion** [comment]
Nanomotion**

It seems to work now, my clone works fine
